version: '3.7'

services:
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: eecamp-wind-mongo
    expose:
      - "27017"
    networks:
      - nginx
    volumes:
      - eecamp-wind-mongo:/data/db

  nginx:
    image: eecamp-wind-nginx
    container_name: eecamp-wind-nginx
    hostname: eecamp-wind-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    networks:
      - nginx
    depends_on:
      - backend
      - frontend

  backend:
    image: eecamp-wind-backend-dev
    container_name: eecamp-wind-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      PORT: "9487"
    ports:
      - "9487:9487"
    expose:
      - "9487"
    networks:
      - nginx
    volumes:
      - ./backend:/source
    x-develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /code/app
        - action: rebuild
          path: ./backend/package.json
    depends_on:
      - mongo

  frontend:
    image: eecamp-wind-frontend-dev
    container_name: eecamp-wind-frontend-dev
    build:
      context: ./frontend
      # context: ./test-frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      PORT: "6987"
    ports:
      - "6987:6987"
    expose:
      - "6987"
    networks:
      - nginx
    volumes:
      - ./frontend:/source
    x-develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /code/src
        - action: rebuild
          path: ./frontend/package.json
    depends_on:
      - backend

networks:
  nginx:
    external: true

volumes:
  eecamp-wind-mongo:

